### ISSUE TITLE
Bugs in base

### ISSUE THREAD

**Issue by ghost** [bzdvdn/amocrm-api-wrapper#3]
There is a BUGS in the method _get_entities() of BaseClient class.
In 57 and 60 lines.

This won't work with params like - `[updated_at][from]': <timedelta>`
`filter_query = {f'filter[{k}]': v for k, v in filters.items()}`
Need to pick up `[` and `]`.

This is a syntax error. `k` doesn't pass to f-string.
`order_query = {f'order[k]': v for k, v in order.items()}`
Need add `{` and `}` around `k`.

**Comment by bzdvdn** [comment]
in v 0.0.9 fix this, support in filters update_at__from, update_at__to
